CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    color VARCHAR(100) NOT NULL,
    avatar VARCHAR(255) NULL,
    password VARCHAR(60) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);